#
#Mon Jun 22 14:02:20 COT 2026
platform=ANY
version=
name=proyecto
unhandledPromptBehavior=ignore
chrome.switches=--disable-infobars,--disable-notifications,--ignore-certificate-errors,--ignore-ssl-errors,--allow-insecure-localhost,--disable-password-manager-reauthentication,--disable-save-password-bubble,--password-store\=basic,--disable-features\=LeakDetection
browserName=chrome
